/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package desarrollo;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.rowset.CachedRowSet;
import logica.DB;
import logica.Utilidades;
import net.sf.jcarrierpigeon.WindowPosition;
import net.sf.jtelegraph.Telegraph;
import net.sf.jtelegraph.TelegraphQueue;
import net.sf.jtelegraph.TelegraphType;

/**
 *
 * @author Usuario
 */
public class AperturaCaja extends javax.swing.JFrame {

    /**
     * Creates new form AperturaCaja
     */
    private DB db = new DB();
    private CachedRowSet data;
    Utilidades utilidades = new Utilidades();
    public AperturaCaja() {
        setUndecorated(true);
        initComponents();
        txtCajaChica.setText("0.0");
        lblFecha.setText(fecha_actual());
        cargarUsuario();
        cargarNumeroCaja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAperturaCaja = new javax.swing.JLabel();
        lblResponsable = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCajaChica = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();
        rbAcepto = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Apertura de Caja");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Al iniciar la apertura de caja usted estara a cargo del inventario hasta el cierre de caja");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/guardar.png"))); // NOI18N
        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/registradora.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addComponent(jLabel1)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Apertura de Caja ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Responsable de Caja");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Fecha y Hora");

        lblAperturaCaja.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAperturaCaja.setForeground(new java.awt.Color(255, 51, 51));

        lblResponsable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResponsable.setForeground(new java.awt.Color(255, 51, 51));

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 51, 51));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Dinero en Caja Chica");

        txtCajaChica.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        txtCajaChica.setForeground(new java.awt.Color(102, 153, 255));
        txtCajaChica.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCajaChica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCajaChicaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCajaChicaKeyReleased(evt);
            }
        });

        txtComentarios.setColumns(20);
        txtComentarios.setLineWrap(true);
        txtComentarios.setRows(5);
        jScrollPane2.setViewportView(txtComentarios);

        rbAcepto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbAcepto.setForeground(new java.awt.Color(0, 204, 0));
        rbAcepto.setText("Acepto");
        rbAcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAceptoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Comentarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAperturaCaja, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(lblResponsable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addComponent(rbAcepto)))
                .addGap(1351, 1351, 1351))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCajaChica, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(lblAperturaCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(lblResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(rbAcepto))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtCajaChica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        abrirCaja();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCajaChicaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCajaChicaKeyReleased
        // TODO add your handling code here:
        logica.Utilidades validar = new logica.Utilidades();
        validar.validarCampoNumericos(txtCajaChica.getText(), txtCajaChica);
    }//GEN-LAST:event_txtCajaChicaKeyReleased

    private void txtCajaChicaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCajaChicaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirCaja();
        }
    }//GEN-LAST:event_txtCajaChicaKeyPressed

    private void rbAceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAceptoActionPerformed
        txtCajaChica.requestFocus();
    }//GEN-LAST:event_rbAceptoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAperturaCaja;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblResponsable;
    private javax.swing.JRadioButton rbAcepto;
    private javax.swing.JTextField txtCajaChica;
    private javax.swing.JTextArea txtComentarios;
    // End of variables declaration//GEN-END:variables

        public void abrirCaja() {
        String comentario = txtComentarios.getText();
        String usuario;
        usuario = System.getProperty("usuario_sistema");
        int usuario_id = Integer.parseInt(usuario);
        if (!rbAcepto.isSelected()) {
            Telegraph tele = new Telegraph("Apertura Caja", "Debe de seleccionar la opcion Acepto primero", TelegraphType.NOTIFICATION_INFO, WindowPosition.TOPRIGHT, 9000);
            TelegraphQueue q = new TelegraphQueue();
            q.add(tele);

        }

        if (rbAcepto.isSelected()) {
            if (txtCajaChica.getText().isEmpty()) {
                Telegraph tele = new Telegraph("Apertura Caja", "Debe de completar el campo Dinero en Caja Chica", TelegraphType.NOTIFICATION_INFO, WindowPosition.TOPRIGHT, 9000);
                TelegraphQueue q = new TelegraphQueue();
                q.add(tele);
            } else {
                Double cajaChica = Double.parseDouble(txtCajaChica.getText());
                String comentarios = txtComentarios.getText();
                System.out.println("Los comentarios son: " + comentarios);
                String querySQL = String.format("INSERT INTO caja(base, ventas_membresia, usuario_sistema_id, ventas_visitas, fecha_apertura, fecha_cierre, total_ingresos, total_egresos, adeudar_creditos, estado, fecha_registro, total_venta, total_recibido, comentarios) VALUES (%s, %s, %s, %s, now(),now(), %s, %s, %s, %s, now(), %s, %s, '%s')", cajaChica, 0, usuario_id, 0, 0, 0, 0, true, 0, 0, comentarios);
                boolean success = db.sqlEjec(querySQL);

                if (success) {

                    Telegraph tele = new Telegraph("Apertura De Caja", "Se ha abierto Correctamente la caja", TelegraphType.NOTIFICATION_DONE, WindowPosition.TOPRIGHT, 9000);
                    TelegraphQueue q = new TelegraphQueue();
                    q.add(tele);
                    utilidades.verificarBackups("backup_abrircaja");
                    this.dispose();

                } else {
                    Telegraph tele = new Telegraph("Apertura De Caja", "No se ha abierto Correctamente la caja", TelegraphType.NOTIFICATION_ERROR, WindowPosition.TOPRIGHT, 9000);
                    TelegraphQueue q = new TelegraphQueue();
                    q.add(tele);
                }
            }

        }

    }

    public String fecha_actual() {

        String fecha = null;
        Calendar fecha_actual = new GregorianCalendar();

        int ano = fecha_actual.get(Calendar.YEAR);
        int mes = fecha_actual.get(Calendar.MONTH);
        int dia = fecha_actual.get(Calendar.DAY_OF_MONTH);
        int hora = fecha_actual.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha_actual.get(Calendar.MINUTE);
        int segundo = fecha_actual.get(Calendar.SECOND);

        fecha = dia + "/" + (mes + 1) + "/" + ano + " " + hora + ":" + minuto + ":" + segundo;
        return fecha;
    }

    public void cargarUsuario() {
        String nombre_usuario;
        String usuario;
        usuario = System.getProperty("usuario_sistema");
        try {
            String nombre = String.format("SELECT primer_nombre FROM usuario_sistema WHERE id=(%s)", usuario);
            data = db.sqlDatos(nombre);

            while (data.next()) {
                nombre_usuario = data.getString("primer_nombre");
                lblResponsable.setText(nombre_usuario);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AperturaCaja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void cargarNumeroCaja() {

        int numCaja = 0;
        int numero;

        try {
            String nombre = String.format("SELECT id FROM caja WHERE total_venta > 0.0");
            data = db.sqlDatos(nombre);
            if (data.size() == 0) {
                lblAperturaCaja.setText("# ".concat(String.valueOf(1)));
            } else {
                while (data.next()) {
                    numCaja = data.getInt("id");
                }
                numero = numCaja + 1;
                lblAperturaCaja.setText("# ".concat(String.valueOf(numero)));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AperturaCaja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
