/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desarrollo;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.rowset.CachedRowSet;
import javax.swing.table.DefaultTableModel;
import logica.DB;

/**
 *
 * @author Usuario
 */
public class CajaDetalleDineroRecibido extends javax.swing.JInternalFrame {

    /**
     * Creates new form DetalleDineroRecibido
     */
    private DB db = new DB();

    public CajaDetalleDineroRecibido(String id, String fecha_apertura, String fecha) {
        initComponents();
        cargarDineroRecibido(id, fecha_apertura, fecha);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTotal = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Detalle Dinero Recibido");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Suma total de Dinero Recibido");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Permite visualizar el  total de dinero recibido en la caja . ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/hoja.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
                        .addGap(97, 97, 97))
                    .addComponent(jLabel1)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(114, 114, 114))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaTotal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTotal;
    // End of variables declaration//GEN-END:variables

    private void cargarDineroRecibido(String id_caja, String fecha_apertura, String fecha_cierre) {
        CachedRowSet data;

        try {
            DefaultTableModel tableModel = new DefaultTableModel(null, new String[]{"USUARIO", "NOMBRE SOCIO", "TIPO DE PAGO", "VALOR DE PAGO", "DESCRIPCIÓN", "DESCUENTO", "FECHA DEL PAGO"});

            String sqlQuery
                    = "SELECT us.primer_nombre AS \"USUARIO\", pago.nombres || ' ' || pago.apellidos AS \"Nombre Socio\", 'VISITAS' AS \"TIPO DE PAGO\", pago.costo AS \"VALOR PAGO\", 'VISITAS' AS \"DESCRIPCIÓN\",0.0 AS \"Descuento\", pago.fecha_registro AS \"FECHA PAGO\"\n"
                    + "FROM pago_visita pago, caja ca, usuario_sistema us\n"
                    + "WHERE ca.estado= false\n"
                    + "AND pago.usuario_sistema_id= us.id\n"
                    + "AND ca.id= " + id_caja
                    + "AND pago.fecha_registro >= '" + fecha_apertura + "' "
                    + "AND pago.fecha_registro <= '" + fecha_cierre + "' "
                    + "UNION\n"
                    + "SELECT sis.primer_nombre ||' ' ||sis.primer_apellido AS \"USUARIO\", s.primer_nombre || ' ' ||  s.segundo_nombre || ' ' || s.primer_apellido || ' ' || s.segundo_apellido AS \"Nombre Socio\", memb.nombre AS \"TIPO DE PAGO\", mem.Pago,'MEMBRESIA', mem_d.descuento, f.fecha_registro \n"
                    + "FROM pago_membresia mem, caja ca, factura f, usuario_sistema sis, membresia_datos mem_d, membresia_usuario mem_u, membresia memb, socio s \n"
                    + "WHERE  mem.fecha_pago >= ca.fecha_apertura\n"
                    + "AND mem.fecha_registro >= '" + fecha_apertura + "' "
                    + "AND mem.fecha_registro <= '" + fecha_cierre + "' "
                    + "AND pago <> 0.0 \n"
                    + "AND mem.valor_adquirido - f.saldo_favor_uso <> 0.0 \n"
                    + "AND sis.id = f.usuario_sistema_id \n"
                    + "AND f.socio_id = s.id \n"
                    + "AND mem.factura_id = f.id \n"
                    + "AND mem.membresiadatos_id = mem_d.id \n"
                    + "AND mem_d.membresia_socio_id = mem_u.id \n"
                    + "AND mem_u.membresia_id = memb.id\n"
                    + "AND ca.id= " + id_caja
                    + "UNION \n"
                    + "SELECT sis.primer_nombre ||' ' ||sis.primer_apellido AS \"USUARIO\", s.primer_nombre || ' ' ||  s.segundo_nombre || ' ' || s.primer_apellido || ' ' || s.segundo_apellido AS \"Nombre Socio\",'Uso Saldo a Favor' :: text,sf.valor_caja * -1 AS Dinero,' ', 0, sf.fecha_registro \n"
                    + "FROM saldofavor sf, usuario_sistema sis, socio s \n"
                    + "WHERE sf.id IN (SELECT Max(sf.id) \n"
                    + "                FROM   saldofavor sf, caja c \n"
                    + "                WHERE  sf.caja_id = c.id \n"
                    + "                AND c.id= " + id_caja
                    + "                AND sf.socio_id IN (SELECT sf.socio_id \n"
                    + "                FROM   saldofavor sf, caja c \n"
                    + "                WHERE  sf.caja_id = c.id \n"
                    + "                AND  c.id= " + id_caja
                    + "                GROUP  BY sf.valor, sf.valor_caja, sf.id \n"
                    + "                HAVING sf.valor - sf.valor_caja <= 0) \n"
                    + "GROUP  BY sf.socio_id) \n"
                    + "AND sf.valor_caja < 0 \n"
                    + "AND sis.id = sf.usuario_sistema_id \n"
                    + "AND s.id = sf.socio_id \n"
                    + "UNION\n"
                    + "SELECT sis.primer_nombre||' '||sis.primer_apellido AS \"USUARIO\", so.primer_nombre || ' ' ||  so.segundo_nombre || ' ' || so.primer_apellido || ' ' || so.segundo_apellido AS \"Nombre Socio\", 'SALDO A FAVOR' AS \"TIPO DE PAGO\", SUM(sf.valor_caja) AS \"Saldo\",'SALDO A FAVOR', 0.0, to_date(null, null) as FECHA\n"
                    + "FROM saldofavor sf, caja c , usuario_sistema sis , socio so\n"
                    + "WHERE sf.caja_id = c.id \n"
                    + "AND sis.id = sf.usuario_sistema_id \n"
                    + "AND so.id = sf.socio_id \n"
                    + "AND c.fecha_apertura BETWEEN '" + fecha_apertura + "'  AND '" + fecha_cierre + "'\n"
                    + "AND sf.socio_id IN (SELECT sf.socio_id\n"
                    + "                    FROM saldofavor sf, caja c\n"
                    + "                    WHERE sf.caja_id = c.id \n"
                    + "                    GROUP BY sf.valor , sf.valor_caja,sf.id)\n"
                    + "                    AND sf.caja_origen is null\n"
                    + "GROUP BY sf.socio_id , sis.primer_nombre , sis.primer_apellido , \"Nombre Socio\" , so.id\n"
                    + "HAVING SUM(sf.valor_caja) > 0";

            System.out.println("La consulta es: " + sqlQuery);
            data = db.sqlDatos(sqlQuery);

            tablaTotal = logica.Utilidades.llenarTabla(data.createCopy(), tableModel, tablaTotal);
        } catch (Exception ex) {
            Logger.getLogger(RegistrarPagoMembresia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
