/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desarrollo;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.rowset.CachedRowSet;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import logica.Acceso;
import logica.CargarCombos;
import logica.DB;
import logica.PlaceHolder;
import logica.Utilidades;
import logica.msj;
import net.sf.jcarrierpigeon.WindowPosition;
import net.sf.jtelegraph.Telegraph;
import net.sf.jtelegraph.TelegraphQueue;
import net.sf.jtelegraph.TelegraphType;

/**
 *
 * @author jucazuse
 */
public class CrearUsuarioSistema extends javax.swing.JInternalFrame {

    private Utilidades utilidades = new Utilidades();
    boolean estadoBD;
    CargarCombos cargarCombo;
    private DB db = new DB();
    SimpleDateFormat format = new SimpleDateFormat("dd/MM/YYYY");
    String usuarioId;
    private AdministrarUsuarioSistema parent;
    private Acceso acceso = new Acceso();

    /**
     * Creates new form UsuarioSistema
     */
    public CrearUsuarioSistema(String usuarioId, AdministrarUsuarioSistema parent) {
        initComponents();
        this.parent = parent;
        cargarCombo = new CargarCombos();
        cargarCombo.llenarComboUnidad(cboSexo, "Masculino", "Femenino");
        txtClave.setEnabled(true);
        traerDatos(usuarioId);
        this.usuarioId = usuarioId;
        txtClave.setVisible(false);
        lbClave.setVisible(false);
        btnCapturarFoto.setVisible(false);
        lbCambioClave.setVisible(true);
        jcEmpleado.setSelected(false);
        
        initgidsoft();

    }

    public CrearUsuarioSistema(AdministrarUsuarioSistema parent) {
        initComponents();
        jcEmpleado.setText("Empleado");
        jcEmpleado.setSelected(false);
        this.parent = parent;
        cargarCombo = new CargarCombos();
        cargarCombo.llenarComboUnidad(cboSexo, "Masculino", "Femenino");
        btnCapturarFoto.setVisible(false);
        lbCambioClave.setVisible(false);
        
        initgidsoft();
    }

    public CrearUsuarioSistema() {
        initComponents();
        jcEmpleado.setText("Empleado");
        jcEmpleado.setSelected(false);
        cargarCombo = new CargarCombos();
        cargarCombo.llenarComboUnidad(cboSexo, "Masculino", "Femenino");
        new PlaceHolder("Clave Generada ...", txtClave);
        btnCapturarFoto.setVisible(false);
        lbCambioClave.setVisible(false);
        
        initgidsoft();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtSegundoNombre = new javax.swing.JTextField();
        txtPrimerApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        txtSegundoApellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jdFechaNaci = new com.toedter.calendar.JDateChooser();
        pnContenedorFoto = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboSexo = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        btnCapturarFoto = new javax.swing.JButton();
        txtClave = new javax.swing.JTextField();
        lbClave = new javax.swing.JLabel();
        jcEmpleado = new javax.swing.JCheckBox();
        lbCambioClave = new javax.swing.JLabel();
        cAdministador = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMenus = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVentanas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Crear Usuario Sistema");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Person-add-black-32.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Permite la creación de un Usuario Sistema (Cliente).");

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(129, 129, 129))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtSegundoNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSegundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundoNombreActionPerformed(evt);
            }
        });
        txtSegundoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSegundoNombreFocusLost(evt);
            }
        });
        txtSegundoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSegundoNombreKeyReleased(evt);
            }
        });

        txtPrimerApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPrimerApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrimerApellidoFocusLost(evt);
            }
        });
        txtPrimerApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrimerApellidoKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Segundo Nombre");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Primer Nombre");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Primer Apellido");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Segundo Apellido");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Fecha de Nacimiento");

        txtPrimerNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPrimerNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrimerNombreFocusLost(evt);
            }
        });
        txtPrimerNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrimerNombreKeyReleased(evt);
            }
        });

        txtSegundoApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSegundoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSegundoApellidoKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Teléfono");

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Correo Electrónico");

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        jdFechaNaci.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pnContenedorFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout pnContenedorFotoLayout = new javax.swing.GroupLayout(pnContenedorFoto);
        pnContenedorFoto.setLayout(pnContenedorFotoLayout);
        pnContenedorFotoLayout.setHorizontalGroup(
            pnContenedorFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnContenedorFotoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnContenedorFotoLayout.setVerticalGroup(
            pnContenedorFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnContenedorFotoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Sexo");

        cboSexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboSexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboSexoKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Identificacion");

        txtIdentificacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIdentificacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdentificacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdentificacionFocusLost(evt);
            }
        });
        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyReleased(evt);
            }
        });

        btnCapturarFoto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCapturarFoto.setText("Capturar Foto");

        txtClave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtClave.setForeground(new java.awt.Color(255, 0, 0));
        txtClave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClaveFocusLost(evt);
            }
        });
        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClaveKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClaveKeyReleased(evt);
            }
        });

        lbClave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbClave.setForeground(new java.awt.Color(255, 0, 0));
        lbClave.setText("Clave");

        jcEmpleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbCambioClave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbCambioClave.setForeground(new java.awt.Color(255, 0, 0));
        lbCambioClave.setText("Cambio de Clave");
        lbCambioClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCambioClaveMouseClicked(evt);
            }
        });

        cAdministador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cAdministador.setText("Administrador");
        cAdministador.setToolTipText("¡IMPORTATE!; Solo activar esta opción si quiere dar permisos a todas las opciones del sistema.");

        tablaMenus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Cod.", "Menú", "Principal", "Permitir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMenus.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaMenus);
        if (tablaMenus.getColumnModel().getColumnCount() > 0) {
            tablaMenus.getColumnModel().getColumn(0).setResizable(false);
            tablaMenus.getColumnModel().getColumn(0).setPreferredWidth(1);
            tablaMenus.getColumnModel().getColumn(1).setPreferredWidth(20);
            tablaMenus.getColumnModel().getColumn(2).setPreferredWidth(20);
            tablaMenus.getColumnModel().getColumn(3).setResizable(false);
            tablaMenus.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jTabbedPane1.addTab("Permisos Menús", jScrollPane1);

        tablaVentanas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaVentanas);

        jTabbedPane1.addTab("Permisos Ventanas", jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnContenedorFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(btnCapturarFoto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbClave, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCambioClave, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrimerApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(4, 4, 4)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jcEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cAdministador)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jcEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cAdministador))
                                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(txtSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jdFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbClave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbCambioClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel5))
                            .addComponent(pnContenedorFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCapturarFoto)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdentificacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyReleased
        utilidades.validarCampoNumericos(txtIdentificacion.getText(), txtIdentificacion);
        if (usuarioId != null) {
            if (txtIdentificacion.getText().trim().length() >= 6) {
                utilidades.buscarIdentificacion(txtIdentificacion.getText().trim(), Integer.valueOf(usuarioId), txtIdentificacion);
            }
        }
    }//GEN-LAST:event_txtIdentificacionKeyReleased

    private void txtIdentificacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdentificacionFocusLost

        if (usuarioId == null) {
            utilidades.buscarIdentificacion(txtIdentificacion.getText(), "estado", "usuario_sistema", 0, txtIdentificacion);
        }

        if (txtIdentificacion.getText().trim().length() < 6) {
            txtIdentificacion.requestFocus();
            msj.show("Informacion", "El campo identificacion debe tener 6 o mas digitos", TelegraphType.NOTIFICATION_WARNING, 4000);
        }
    }//GEN-LAST:event_txtIdentificacionFocusLost

    private void txtIdentificacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdentificacionFocusGained

    }//GEN-LAST:event_txtIdentificacionFocusGained

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        utilidades.validarCampoNumericos(txtTelefono.getText(), txtTelefono);
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed

    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtSegundoApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundoApellidoKeyReleased
        utilidades.validarCamposTexto(txtSegundoApellido.getText(), txtSegundoApellido);
    }//GEN-LAST:event_txtSegundoApellidoKeyReleased

    private void txtPrimerApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimerApellidoKeyReleased
        utilidades.validarCamposTexto(txtPrimerApellido.getText(), txtPrimerApellido);
    }//GEN-LAST:event_txtPrimerApellidoKeyReleased

    private void txtSegundoNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundoNombreKeyReleased
        utilidades.validarCamposTexto(txtSegundoNombre.getText(), txtSegundoNombre);
    }//GEN-LAST:event_txtSegundoNombreKeyReleased

    private void txtSegundoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSegundoNombreFocusLost

    }//GEN-LAST:event_txtSegundoNombreFocusLost

    private void txtSegundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoNombreActionPerformed

    private void txtClaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyReleased
    }//GEN-LAST:event_txtClaveKeyReleased

    private void txtClaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClaveFocusLost
        if (txtClave.getText().length() < 6) {
            Telegraph tele = new Telegraph("Advertencia", "El  campo clave debe contener 6 o mas digitos", TelegraphType.NOTIFICATION_INFO, WindowPosition.TOPRIGHT, 2000);
            TelegraphQueue q = new TelegraphQueue();
            q.add(tele);
            txtClave.requestFocus();
        }
    }//GEN-LAST:event_txtClaveFocusLost

    private void txtPrimerApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrimerApellidoFocusLost
        if (!txtPrimerApellido.getText().isEmpty()) {
            String clave = txtPrimerApellido.getText().substring(0, 1).concat(txtIdentificacion.getText()).toUpperCase();
            txtClave.setText(clave);
        } else {
            txtClave.setText("");
        }
    }//GEN-LAST:event_txtPrimerApellidoFocusLost

    private void txtPrimerNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimerNombreKeyReleased
        utilidades.validarCamposTexto(txtPrimerNombre.getText(), txtPrimerNombre);
    }//GEN-LAST:event_txtPrimerNombreKeyReleased

    private void txtPrimerNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrimerNombreFocusLost
    }//GEN-LAST:event_txtPrimerNombreFocusLost

    private void lbCambioClaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCambioClaveMouseClicked
        CambioClave cambioClave;
        cambioClave = new CambioClave(Integer.valueOf(usuarioId),this);
        cambioClave.setVisible(true);
        cambioClave.setAlwaysOnTop(true);
        cambioClave.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_lbCambioClaveMouseClicked

    private void cboSexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboSexoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            guardar();
        }
    }//GEN-LAST:event_cboSexoKeyPressed

    private void txtClaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            guardar();
        }
    }//GEN-LAST:event_txtClaveKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapturarFoto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox cAdministador;
    private javax.swing.JComboBox cboSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox jcEmpleado;
    private com.toedter.calendar.JDateChooser jdFechaNaci;
    private javax.swing.JLabel lbCambioClave;
    private javax.swing.JLabel lbClave;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JPanel pnContenedorFoto;
    private javax.swing.JTable tablaMenus;
    private javax.swing.JTable tablaVentanas;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    
    private void guardar() {
        String primerNombre = txtPrimerNombre.getText();
        String segundoNombre = txtSegundoNombre.getText();
        String primerApellido = txtPrimerApellido.getText();
        String segundoApellido = txtSegundoApellido.getText();
        String email = txtCorreo.getText();
        String telefono = txtTelefono.getText();
        String claveUpdate = txtClave.getText();
        String querySQL;
        String clave = txtClave.getText().trim();
        boolean success;
        boolean empleado = jcEmpleado.isSelected();
        boolean admin = cAdministador.isSelected();
        boolean estado;
        if (jcEmpleado.getText().contains("Des")) {
            estado = jcEmpleado.isSelected();
            if (estado == true) {
                estado = false;
            } else {
                estado = estadoBD;
            }
        } else {
            estado = jcEmpleado.isSelected();
            if (estado == true) {
                estado = true;
            } else {
                estado = estadoBD;
            }
        }
        Date fechaNaci = jdFechaNaci.getDate();
        String fechaNacimiento = "NULL";
        if (fechaNaci != null) {
            fechaNacimiento = "'" + format.format(fechaNaci) + "'";
        }
        String identificacion = txtIdentificacion.getText();
        String sexo = String.valueOf(cboSexo.getSelectedItem());
        if (!txtIdentificacion.getText().isEmpty()) {
            if (!txtPrimerNombre.getText().isEmpty()) {
                if (!txtPrimerApellido.getText().isEmpty()) {
                    if (!cboSexo.getSelectedItem().toString().isEmpty()) {
                        if (usuarioId != null) {
                            querySQL = String.format("UPDATE usuario_sistema SET identificacion='%s',primer_nombre='%s',segundo_nombre='%s',primer_apellido='%s',segundo_apellido='%s',fecha_nacimiento=%s,telefono='%s',email='%s',sexo='%s',estado=%s , admin = %s WHERE id='%s'", identificacion, primerNombre, segundoNombre, primerApellido, segundoApellido, fechaNacimiento, telefono, email, sexo, estado, admin, usuarioId);
                            success = db.sqlEjec(querySQL);
                            if (success) {
                                actualizarPermisos();
                                this.dispose();
                                parent.obtenerUsuariosSistema(true);
                                Telegraph tele = new Telegraph("Usuario Actualizado", "Se ha actualizado Correctamente el Usuario", TelegraphType.NOTIFICATION_ADD, WindowPosition.TOPRIGHT, 9000);
                                TelegraphQueue q = new TelegraphQueue();
                                q.add(tele);
                                return;
                            }
                        } else {
                            querySQL = String.format("INSERT INTO usuario_sistema(clave,identificacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,sexo,fecha_nacimiento,telefono,email,estado,empleado,fecha_registro,admin) VALUES(MD5('%s'),'%s','%s','%s','%s','%s','%s',%s,'%s','%s',true,%s,now(),%s);", clave, identificacion, primerNombre, segundoNombre, primerApellido, segundoApellido, sexo, fechaNacimiento, telefono, email, empleado, admin);
                            success = db.sqlEjec(querySQL);
                            if (success) {
                                System.out.println("Usuario creado con ID " + db.getKeys());
                                usuarioId = String.valueOf(db.getKeys());
                                if (parent != null) {
                                    parent.obtenerUsuariosSistema(true);
                                }

                                crearPermisos();
                                //this.dispose();
                                Telegraph tele = new Telegraph("Usuario Registrado", "Se ha registrado Correctamente el Usuario", TelegraphType.NOTIFICATION_ADD, WindowPosition.TOPRIGHT, 9000);
                                TelegraphQueue q = new TelegraphQueue();
                                q.add(tele);
                            }
                        }

                    } else {
                        utilidades.llamarMensaje("Sexo");
                    }
                } else {
                    utilidades.llamarMensaje("Primer Apellido");
                }
            } else {
                utilidades.llamarMensaje("Primer Nombre");
            }
        } else {
            utilidades.llamarMensaje("Identificacion");
        }
    }
    public void traerDatos(String id) {
        CachedRowSet data;
        String querySQL;
        querySQL = String.format("SELECT us.estado,us.identificacion,us.primer_nombre,us.segundo_nombre,us.primer_apellido,us.segundo_apellido,us.clave,us.fecha_nacimiento,us.email,us.telefono,us.sexo,us.empleado,us.estado,us.foto , us.admin \n"
                + "FROM usuario_sistema us\n"
                + "WHERE us.id= '%s';", id);
        data = db.sqlDatos(querySQL);
        try {
            while (data.next()) {
                estadoBD = data.getBoolean("estado");
                if (id.equals("1")) {
                    jcEmpleado.setVisible(false);
                } else {
                    if (data.getBoolean("estado") == true) {
                        jcEmpleado.setText("Desactivar");
                    } else {
                        jcEmpleado.setText("Activar");
                    }
                }
                txtClave.setText(data.getString("clave"));
                txtIdentificacion.setText(data.getString("identificacion"));
                txtPrimerNombre.setText(data.getString("primer_nombre"));
                txtSegundoNombre.setText(data.getString("segundo_nombre"));
                txtPrimerApellido.setText(data.getString("primer_apellido"));
                txtSegundoApellido.setText(data.getString("segundo_apellido"));
                jcEmpleado.setSelected(data.getBoolean("empleado"));
                cAdministador.setSelected(data.getBoolean("admin"));
                Date fechaNacimiento = data.getDate("fecha_nacimiento");
                if (fechaNacimiento != null) {
                    jdFechaNaci.setDate(fechaNacimiento);
                }
                txtCorreo.setText(data.getString("email"));
                cboSexo.setSelectedItem(data.getString("sexo"));
                if (data.getBytes("foto") != null) {
                    System.out.println(data.getBytes("foto"));
                    ImageIcon foto = new ImageIcon(data.getBytes("foto"));
                    lblFoto.setIcon(foto);
                }
                txtTelefono.setText(data.getString("telefono"));
                if (data.getBoolean("estado") == false) {
                    jcEmpleado.setText("Activar");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarPagoMembresia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public int buscarId(String usarioId) {
        CachedRowSet data;
        int id = 0;
        String querySQL = String.format("SELECT id FROM usuario_sistema WHERE identificacion = '%s' ", usarioId);
        data = db.sqlDatos(querySQL);
        try {
            if (data.next()) {
                id = data.getInt("id");
                return id;
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarPagoMembresia.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    
    
    public void initgidsoft(){
        tablaMenus();
    }
    
    public void tablaMenus(){
        try {
            //Si usuario aun no se ha crado darle valor de 0 para que solo traiga los menus disponibles
            String usuario = "0";
            if(usuarioId != null){
                usuario = usuarioId;
            }
            CachedRowSet data;
            DefaultTableModel tableModel = (DefaultTableModel) tablaMenus.getModel();
            data = db.sqlDatos("SELECT menu.*, (SELECT permitir FROM sistema_menu_usuario WHERE usuario_id = "+usuario+" AND menu_id = menu.id ) AS Permitir FROM sistema_menu menu");
            tablaMenus = logica.Utilidades.llenarTablaPermisos(data.createCopy(), tableModel, tablaMenus);
        } catch (SQLException ex) {
            Logger.getLogger(CrearUsuarioSistema.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void crearPermisos() {
        crearPermisosMenus();
    }
    
    private void actualizarPermisos(){
        actualizarPermisosMenu();
    }

    private void crearPermisosMenus() {
        int registros = tablaMenus.getRowCount();
        for (int i = 0; i < registros; i++) {
            acceso.crearPermisoMenu(usuarioId, tablaMenus.getValueAt(i, 0), tablaMenus.getValueAt(i, 3));
        }
    }
    
    private void actualizarPermisosMenu(){
        int registros = tablaMenus.getRowCount();
        for (int i = 0; i < registros; i++) {
            
            Object menuId = tablaMenus.getValueAt(i, 0);
            Object permitir = tablaMenus.getValueAt(i, 3);
            
            if(acceso.existePermisoMenu(usuarioId, menuId)){
                acceso.actualizarPermisoMenu(usuarioId, menuId, permitir);
            }else{
                acceso.crearPermisoMenu(usuarioId, menuId, permitir);
            }
        }
    }

}