/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desarrollo;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sql.rowset.CachedRowSet;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import logica.Acceso;
import logica.DB;
import logica.Fondo;
import logica.PlaceHolder;
import logica.Utilidades;
import puerta.Puerta;

/**
 *
 * @author GID
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
    private DB db = new DB();
    private CachedRowSet data;
    private Utilidades utiles = new Utilidades();
    private PlaceHolder placeholder;
    public InputStream foto1 = this.getClass().getResourceAsStream("/imagen/biofisic_logo.png");

    public Frame() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setTitle("BioFisic GYM - > Sistema de Control Acceso");
        this.setVisible(true);
        txtBuscar.requestFocusInWindow();
        setIconImage(new ImageIcon(getClass().getResource("/imagen/icon_biofisic.png")).getImage());
        PlaceHolder placeHolder = new PlaceHolder("Buscar Socios ...", txtBuscar);
        cargarImagen(escritorio, foto1);
        comprobarPermisosMenu();
    }

    public Frame(String id) throws SQLException, ParseException {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setTitle("Biofisic GYM - > Sistema de Control Acceso");
        this.setVisible(true);
        txtBuscar.requestFocusInWindow();
        txtBuscar.setText(id);
        buscar();
        cargarImagen(escritorio, foto1);
        setIconImage(new ImageIcon(getClass().getResource("/imagen/icono_biofisic.png")).getImage());

    }

    public void cargarImagen(JDesktopPane jDeskp, InputStream fileImagen) {
        try {
            BufferedImage image = ImageIO.read(fileImagen);
            jDeskp.setBorder(new Fondo(image));
        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void agregarInternalFrame(JDesktopPane desktop, JInternalFrame internal) { //esta funciÃ³n permite agregar un internal frame a un jframe rapidamente :)
        desktop.add(internal);
        Utilidades.centrarInternalFrame(internal);
    }

    public void agregarInternalFrame(JInternalFrame internal) { //esta funciÃ³n permite agregar un internal frame a un jframe rapidamente :)
        escritorio.add(internal);
        Utilidades.centrarInternalFrame(internal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        btnRegistrarVisita = new javax.swing.JButton();
        btnCrearSocio = new javax.swing.JButton();
        btnCierreCaja = new javax.swing.JButton();
        btnRegistrarEgreso = new javax.swing.JButton();
        btnCrearMembresia = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        bInicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bPuerta1 = new javax.swing.JButton();
        MenuAplicacion = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        mAcciones = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mAdministracion = new javax.swing.JMenu();
        mMembresia = new javax.swing.JMenuItem();
        mEmpleado = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        mIngreso = new javax.swing.JMenuItem();
        mEgreso = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        itemAdministrarPuerta = new javax.swing.JMenuItem();
        mInformes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        escritorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                escritorioKeyTyped(evt);
            }
        });

        btnRegistrarVisita.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarVisita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarVisita.setText("REGISTRAR VISITA (F3)");
        btnRegistrarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVisitaActionPerformed(evt);
            }
        });

        btnCrearSocio.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearSocio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrearSocio.setText("CREAR SOCIO (F2)");
        btnCrearSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSocioActionPerformed(evt);
            }
        });

        btnCierreCaja.setBackground(new java.awt.Color(255, 255, 255));
        btnCierreCaja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCierreCaja.setText("CIERRE DE CAJA (F7)");
        btnCierreCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCierreCajaActionPerformed(evt);
            }
        });

        btnRegistrarEgreso.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarEgreso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarEgreso.setText("REGISTRAR EGRESO (F5)");
        btnRegistrarEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEgresoActionPerformed(evt);
            }
        });

        btnCrearMembresia.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearMembresia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrearMembresia.setText("CREAR MEMBRESÍA (F6)");
        btnCrearMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMembresiaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("www.gidsoft.org");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscar.setToolTipText("BUSCAR UN SOCIO...");
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/buscar.png"))); // NOI18N
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/home.png"))); // NOI18N
        bInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicioActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/gym.jpg"))); // NOI18N

        bPuerta1.setBackground(new java.awt.Color(153, 153, 153));
        bPuerta1.setForeground(new java.awt.Color(204, 204, 204));
        bPuerta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icono_puerta.png"))); // NOI18N
        bPuerta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPuerta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(bInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPuerta1)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(bBuscar)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPuerta1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        escritorio.setLayer(btnRegistrarVisita, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnCrearSocio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnCierreCaja, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnRegistrarEgreso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnCrearMembresia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addComponent(btnCrearSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnRegistrarEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addComponent(btnRegistrarVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCrearMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCierreCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnRegistrarEgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnCierreCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        MenuAplicacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        mArchivo.setText("Archivo");
        mArchivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem13.setText("Copias de Seguridad");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        mArchivo.add(jMenuItem13);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem6.setText("Cerrar Sesión");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mArchivo.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem7.setText("Salir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mArchivo.add(jMenuItem7);

        MenuAplicacion.add(mArchivo);

        mAcciones.setText("Acciones");
        mAcciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem11.setText("Registrar Entrada Automática");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        mAcciones.add(jMenuItem11);
        mAcciones.add(jSeparator1);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem5.setText("Crear Socio");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mAcciones.add(jMenuItem5);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem4.setText("Crear Membresía");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mAcciones.add(jMenuItem4);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem9.setText("Crear Usuario Sistema");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mAcciones.add(jMenuItem9);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem1.setText("Cerrar Caja");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mAcciones.add(jMenuItem1);

        MenuAplicacion.add(mAcciones);

        mAdministracion.setText("Administración");
        mAdministracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mMembresia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mMembresia.setText("Administrar Membresías");
        mMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMembresiaActionPerformed(evt);
            }
        });
        mAdministracion.add(mMembresia);

        mEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mEmpleado.setText("Administrar Usuario Sistema");
        mEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmpleadoActionPerformed(evt);
            }
        });
        mAdministracion.add(mEmpleado);
        mAdministracion.add(separador);

        mIngreso.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIngresoActionPerformed(evt);
            }
        });
        mAdministracion.add(mIngreso);

        mEgreso.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mEgreso.setText("Administrar Egresos");
        mEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEgresoActionPerformed(evt);
            }
        });
        mAdministracion.add(mEgreso);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem8.setText("Administrar Visitas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mAdministracion.add(jMenuItem8);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem12.setText("Administrar Caja");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        mAdministracion.add(jMenuItem12);

        itemAdministrarPuerta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        itemAdministrarPuerta.setText("Administrar Puerta");
        itemAdministrarPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAdministrarPuertaActionPerformed(evt);
            }
        });
        mAdministracion.add(itemAdministrarPuerta);

        MenuAplicacion.add(mAdministracion);

        mInformes.setText("Informes");
        mInformes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem2.setText("Ventas del día");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mInformes.add(jMenuItem2);
        mInformes.add(jSeparator2);

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem14.setText("Socios");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        mInformes.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem15.setText("Asistencia");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        mInformes.add(jMenuItem15);

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem16.setText("Caja");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        mInformes.add(jMenuItem16);

        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem17.setText("Pagos");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        mInformes.add(jMenuItem17);

        jMenuItem18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem18.setText("Membresias");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        mInformes.add(jMenuItem18);

        MenuAplicacion.add(mInformes);

        setJMenuBar(MenuAplicacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMembresiaActionPerformed
        agregarInternalFrame(escritorio, new AdministrarMembresia());
    }//GEN-LAST:event_mMembresiaActionPerformed

    private void mEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEmpleadoActionPerformed
        agregarInternalFrame(escritorio, new AdministrarUsuarioSistema());
    }//GEN-LAST:event_mEmpleadoActionPerformed

    private void mIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIngresoActionPerformed
        //agregarInternalFrame(escritorio, new AdministrarIngresos());
    }//GEN-LAST:event_mIngresoActionPerformed

    private void mEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEgresoActionPerformed
        agregarInternalFrame(escritorio, new AdministrarEgresos());
    }//GEN-LAST:event_mEgresoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        agregarInternalFrame(escritorio, new CrearSocio());        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        agregarInternalFrame(escritorio, new CrearMembresia());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        int response = JOptionPane.showConfirmDialog(null, "¿Realmente desea Salir?", "Salir",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void btnCrearMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMembresiaActionPerformed
        agregarInternalFrame(escritorio, new CrearMembresia());
    }//GEN-LAST:event_btnCrearMembresiaActionPerformed

    private void btnCrearSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSocioActionPerformed
        agregarInternalFrame(escritorio, new CrearSocio());     }//GEN-LAST:event_btnCrearSocioActionPerformed

    private void btnRegistrarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVisitaActionPerformed
        agregarInternalFrame(escritorio, new RegistrarVisita());
    }//GEN-LAST:event_btnRegistrarVisitaActionPerformed

    private void btnRegistrarEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEgresoActionPerformed
        agregarInternalFrame(escritorio, new RegistrarEgreso());
    }//GEN-LAST:event_btnRegistrarEgresoActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        agregarInternalFrame(escritorio, new AdministrarVisita());
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        cierreCaja();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        agregarInternalFrame(escritorio, new CrearUsuarioSistema());
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void btnCierreCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCierreCajaActionPerformed
        // TODO add your handling code here:
        cierreCaja();
    }//GEN-LAST:event_btnCierreCajaActionPerformed


    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        RegistroEntradaAutomatica miFrameBloqueo1 = new RegistroEntradaAutomatica();
        miFrameBloqueo1.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        agregarInternalFrame(escritorio, new AdministrarCaja());
    }//GEN-LAST:event_jMenuItem12ActionPerformed
    private void bPuerta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPuerta1ActionPerformed
        Puerta pp = new puerta.Puerta();
        pp.openDoor();
    }//GEN-LAST:event_bPuerta1ActionPerformed

    private void bInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicioActionPerformed
        JInternalFrame items[] = escritorio.getAllFrames();
        for (int i = 0; i < items.length; i++) {
            try {
                items[i].setClosed(true); //cerrar todos los internal frames
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        txtBuscar.requestFocusInWindow(); //darle foco al buscador
    }//GEN-LAST:event_bInicioActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        try {
            buscar();
        } catch (SQLException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                buscar();
            } catch (SQLException | ParseException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            btnCrearSocio.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F3) {
            btnRegistrarVisita.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            btnRegistrarEgreso.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F6) {
            btnCrearMembresia.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F7) {
            btnCierreCaja.doClick();
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void bPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAbrirPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirPuertaActionPerformed
        Thread t1 = new Thread(new Runnable() {
            public void run() {
                try {
                    Process proc = Runtime.getRuntime().exec("java -jar puerta.jar");
                    proc.waitFor();
                    // Then retreive the process output
                    InputStream in = proc.getInputStream();
                    InputStream err = proc.getErrorStream();

                    byte b[] = new byte[in.available()];
                    in.read(b, 0, b.length);
                    System.out.println(new String(b));

                    byte c[] = new byte[err.available()];
                    err.read(c, 0, c.length);
                    System.out.println(new String(c));
                } catch (IOException | InterruptedException ex) {
                    Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t1.start();
    }//GEN-LAST:event_btnAbrirPuertaActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.dispose();
        login login = new login();
        login.setVisible(true);

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void escritorioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_escritorioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_escritorioKeyTyped

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        agregarInternalFrame(escritorio, new VentasDia());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        agregarInternalFrame(escritorio, new CopiasSeguridad());
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        agregarInternalFrame(escritorio, new InformeSocio());
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        agregarInternalFrame(escritorio, new InformeAsistencia());
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        agregarInternalFrame(escritorio, new InformeCaja());
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        agregarInternalFrame(escritorio, new InformePagos());
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        agregarInternalFrame(escritorio, new InformeMembresia());
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void itemAdministrarPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAdministrarPuertaActionPerformed
        try {
            agregarInternalFrame(escritorio, new AdministrarPuerta());
        } catch (SQLException | IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemAdministrarPuertaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuAplicacion;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bInicio;
    private javax.swing.JButton bPuerta1;
    private javax.swing.JButton btnCierreCaja;
    private javax.swing.JButton btnCrearMembresia;
    private javax.swing.JButton btnCrearSocio;
    private javax.swing.JButton btnRegistrarEgreso;
    private javax.swing.JButton btnRegistrarVisita;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itemAdministrarPuerta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mAcciones;
    private javax.swing.JMenu mAdministracion;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenuItem mEgreso;
    private javax.swing.JMenuItem mEmpleado;
    private javax.swing.JMenu mInformes;
    private javax.swing.JMenuItem mIngreso;
    private javax.swing.JMenuItem mMembresia;
    private javax.swing.JPopupMenu.Separator separador;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    public void nombreResponsable() {
        String querySQL = "SELECT nombre_usuario FROM usuario_sistema WHERE id= (SELECT usuario_sistema_id FROM caja WHERE usuario_sistema_id = '2')";
        data = db.sqlDatos(querySQL);

    }

    public void aperturaCaja() {
        try {
            String querySQL = "SELECT estado, total_venta  FROM caja ORDER BY id DESC LIMIT 1";
            data = db.sqlDatos(querySQL);

            if (data.size() == 0) {
                AperturaCaja aperturaCaja = new AperturaCaja();
                aperturaCaja.setVisible(true);
                aperturaCaja.setLocationRelativeTo(this);
                aperturaCaja.setAlwaysOnTop(true);
                return;
            }

            while (data.next()) {

                boolean estado = data.getBoolean("estado");

                if ((estado == false)) {
                    AperturaCaja aperturaCaja = new AperturaCaja();
                    aperturaCaja.setVisible(true);
                    aperturaCaja.setLocationRelativeTo(this);
                    aperturaCaja.setAlwaysOnTop(true);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CierreCaja.class.getName()).log(Level.WARNING, "Error SQL  JC", ex);
        }
    }

    public void cierreCaja() {
        try {
            String querySQL = "SELECT estado, total_venta  FROM caja ORDER BY id DESC LIMIT 1";
            data = db.sqlDatos(querySQL);
            while (data.next()) {
                boolean estado = data.getBoolean("estado");
                if ((estado == true)) {
                    CierreCaja cierreCaja = new CierreCaja(this);
                    Frame.escritorio.add(cierreCaja);
                    cierreCaja.toFront();
                    cierreCaja.setVisible(true);
                    cierreCaja.moveToFront();
                    cierreCaja.setLocation(150, 50);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CierreCaja.class.getName()).log(Level.WARNING, "Error SQL  JC", ex);
        }
    }

    private void buscar() throws SQLException, ParseException {
        int usuarioId = utiles.esUsuarioUnico(txtBuscar.getText(), true);
        if (usuarioId == -1) {
            agregarInternalFrame(escritorio, new ListadoSocios(txtBuscar.getText(), this));
        } else {
            agregarInternalFrame(new VerSocio(usuarioId));
        }
    }

    private void comprobarPermisosMenu() {

        //Si no es Administrador ... comprobar permisos
        if (!Acceso.esAdmin()) {

            Acceso acceso = new Acceso();

            int menus = MenuAplicacion.getMenuCount();

            for (int i = 0; i < menus; i++) {
                JMenu menu = MenuAplicacion.getMenu(i);
                int elementosMenu = menu.getMenuComponentCount();
                int elementosOcultos = 0; //Cantidad de submenus que no se mostraran

                Component[] sub = menu.getMenuComponents();

                for (Component componente : sub) {
                    if (componente instanceof JMenuItem) {
                        JMenuItem elementoMenu = (JMenuItem) componente;
                        boolean visible = acceso.menuPermitido(elementoMenu.getText(), menu.getText());
                        elementoMenu.setVisible(visible);
                        if (!visible) {
                            elementosOcultos++;
                        }
                    }
                }

                //Si el menu padre no tiene elementos visibles, ocultarlo
                menu.setVisible(elementosMenu != elementosOcultos);

            }
        }
    }
}
